"""crate Rekap,Cetak,Terima

Revision ID: 109d4760c5d9
Revises: 
Create Date: 2020-07-20 15:54:31.039785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '109d4760c5d9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rekap',
    sa.Column('nomor', sa.Integer(), nullable=False),
    sa.Column('sarpelkes', sa.String(length=55), nullable=False),
    sa.Column('nomorwo', sa.String(length=8), nullable=False),
    sa.Column('tahun', sa.Integer(), nullable=True),
    sa.Column('agung', sa.Integer(), nullable=True),
    sa.Column('andi', sa.Integer(), nullable=True),
    sa.Column('azizil', sa.Integer(), nullable=True),
    sa.Column('ilham', sa.Integer(), nullable=True),
    sa.Column('sandra', sa.Integer(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('keterangan', sa.String(length=55), nullable=True),
    sa.Column('tgl_kirim', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('nomor')
    )
    op.create_table('terima',
    sa.Column('nomor', sa.Integer(), nullable=False),
    sa.Column('tanggal', sa.DateTime(), nullable=True),
    sa.Column('jumlah', sa.Integer(), nullable=True),
    sa.Column('sarpelkes', sa.String(length=55), nullable=False),
    sa.Column('nomorwo', sa.String(length=8), nullable=False),
    sa.Column('petugas', sa.String(length=25), nullable=True),
    sa.PrimaryKeyConstraint('nomor')
    )
    op.create_index(op.f('ix_terima_tanggal'), 'terima', ['tanggal'], unique=False)
    op.create_table('cetak',
    sa.Column('nomor', sa.Integer(), nullable=False),
    sa.Column('jumlah', sa.Integer(), nullable=True),
    sa.Column('petugas', sa.String(length=21), nullable=False),
    sa.Column('tanggal', sa.DateTime(), nullable=True),
    sa.Column('no_rekap', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['no_rekap'], ['rekap.nomor'], ),
    sa.PrimaryKeyConstraint('nomor')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cetak')
    op.drop_index(op.f('ix_terima_tanggal'), table_name='terima')
    op.drop_table('terima')
    op.drop_table('rekap')
    # ### end Alembic commands ###
